CREATE TABLE IF NOT EXISTS admin_users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE,
    roles JSON NOT NULL,
    password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
